security:
    password_hashers:
        Symfony\Component\Security\Core\User\InMemoryUser: plaintext

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: 'admin'
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }