version: "3"

services:
  web:
    build: .
    ports:
      - "80:80"
      - "1443:8080" # Add this line to expose WebSocket port
    volumes:
      - .:/var/www/html

  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root_secret