version: '3.8'

services:
  php:
    image: php:8.2-fpm
    container_name: symfony-php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - PHP_INI_UPLOAD_MAX_FILESIZE=1000M
      - PHP_INI_POST_MAX_SIZE=1000M
    networks:
      - symfony-network

  nginx:
    image: nginx:latest
    container_name: symfony-nginx
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - symfony-network

  db:
    image: mysql:8.0
    container_name: symfony-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: filelink_db
      MYSQL_USER: andrz
      MYSQL_PASSWORD: user
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - symfony-network

networks:
  symfony-network:
